AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  mailgun-receiver

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 29
    Tracing: Active

Resources:
  MailgunTopic:
    Type: AWS::SNS::Topic

  MailgunTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
        - AttributeName: "Message.Id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Id"
          KeyType: "HASH"
        - AttributeName: "Message.Id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "mailgunTable"

  MailgunStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/mailgun-store/
      Handler: lambda.handler
      Environment:
        Variables:
          WEBHOOK_TOPIC: !Ref MailgunTopic
      Policies:
        - AWSLambdaDynamoDBExecutionRole
        - DynamoDBCrudPolicy:
            TableName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MailgunTopic.TopicName
      Events:
        StoreData:
          Type: Api
          Properties:
            Path: /
            Method: post
        GetData:
          Type: Api
          Properties:
            Path: /
            Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MailgunStoreApi:
    Description: "API Gateway endpoint URL for Prod stage for Mail Gun Store function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  MailgunStoreFunction:
    Description: "Mailgun Store Lambda Function ARN"
    Value: !GetAtt MailgunStoreFunction.Arn

  MailgunStoreFunctionIamRole:
    Description: "Implicit IAM Role created for Mailgun Store function"
    Value: !GetAtt MailgunStoreFunctionRole.Arn

  MailgunTopicArn:
    Description: "A webhook event SNS topic Arn"
    Value: !Ref MailgunTopic

  MailgunTopicName:
    Description: "A name of the webhook SNS topic"
    Value: !GetAtt MailgunTopic.TopicName
