AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  mailgun-receiver

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 29
    Tracing: Active

Resources:
  WebhookTopic:
    Type: AWS::SNS::Topic

  MailgunStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/mailgun-store/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          WEBHOOK_TOPIC: !Ref WebhookTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt WebhookTopic.TopicName
      Events:
        StoreData:
          Type: Api
          Properties:
            Path: /
            Method: post
        GetData:
          Type: Api
          Properties:
            Path: /
            Method: get
  MailgunTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
        - AttributeName: "Event"
          AttributeType: "S"
        - AttributeName: "RecipientDomain"
          AttributeType: "S"
        - AttributeName: "Recipient"
          AttributeType: "S"
        - AttributeName: "Message.Id"
          AttributeType: "S"
        - AttributeName: "Message.Headers.To"
          AttributeType: "S"
        - AttributeName: "Message.Headers.From"
          AttributeType: "S"
        - AttributeName: "Message.Headers.Subject"
          AttributeType: "S"
        - AttributeName: "Message.Size"
          AttributeType: "S"
        - AttributeName: "Timestamp"
          AttributeType: "N"
        - AttributeName: "Signature.Token"
          AttributeType: "S"
        - AttributeName: "Signature.Signature"
          AttributeType: "S"
        - AttributeName: "Signature.Timestamp"
          AttributeType: "S"
        - AttributeName: "Storage.url"
          AttributeType: "S"
        - AttributeName: "Storage.key"
          AttributeType: "S"
        - AttributeName: "Envelope.SendingIp"
          AttributeType: "S"
        - AttributeName: "Envelope.Sender"
          AttributeType: "S"
        - AttributeName: "Envelope.Transport"
          AttributeType: "S"
        - AttributeName: "Envelope.Targets"
          AttributeType: "S"
        - AttributeName: "DeliveryStatus.Tls"
          AttributeType: "S"
        - AttributeName: "DeliveryStatus.MxHost"
          AttributeType: "S"
        - AttributeName: "DeliveryStatus.AttemptNo"
          AttributeType: "N"
        - AttributeName: "DeliveryStatus.Description"
          AttributeType: "S"
        - AttributeName: "DeliveryStatus.SessionSeconds"
          AttributeType: "N"
        - AttributeName: "DeliveryStatus.Utf8"
          AttributeType: "S"
        - AttributeName: "DeliveryStatus.Code"
          AttributeType: "N"
        - AttributeName: "DeliveryStatus.Message"
          AttributeType: "S"
        - AttributeName: "DeliveryStatus.CertificateVerified"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Id"
          KeyType: "HASH"
        - AttributeName: "Message.Id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "mailGunTable"
  MailTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: !Ref NotificationEmail

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MailgunStoreApi:
    Description: "API Gateway endpoint URL for Prod stage for Mail Gun Store function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  MailgunStoreFunction:
    Description: "Mailgun Store Lambda Function ARN"
    Value: !GetAtt MailGunStoreFunction.Arn

  MailgunStoreFunctionIamRole:
    Description: "Implicit IAM Role created for Mailgun Store function"
    Value: !GetAtt MailgunStoreFunctionRole.Arn

    WebhookTopicArn:
      Description: "A webhook event SNS topic Arn"
      Value: !Ref WebhookTopic

    WebhookTopicName:
      Description: "A name of the webhook SNS topic"
      Value: !GetAtt WebhookTopic.TopicName
